### ISSUE TITLE
Problem with NGINX

### ISSUE THREAD

**Issue by dmpvost** [mvisonneau/docker-generatedata#5]
Hi, thank for this docker!

I'm trying to run the API of this docker, but it didn't work

1. I would like to have this option maybe as a param of configuration of the docker

2. I have change the setting, put it on docker, it work ,but after nginx lock everything, and I didn't know enough nginx for unlock this possibility

any help?
Thank

**Comment by mvisonneau** [comment]
I am sorry but I do not understand your issue. Can you please be more specific about what you are trying to achieve? 🤔

**Comment by dmpvost** [comment]
Okay, 

On the projet of "generatedata" it's possible to active on settings.php

> $apiEnabled = true;

https://benkeen.github.io/generatedata/api.html#enable

Normally, this activate the API for generatedata on URL  : http://yoursite/api/v1/data

I have update the file setting.php, run a new docker, and I have some error with NGINX when I try to get this url.
I think it didn't work because of nginx on the docker

I'm trying to achieve to have a docker which can have this API ready to use.

`GD_API_ENABLE` as a parameter

It would be nice if we have a new option on this docker like 
I hope I made a better explanation ;)

**Comment by mvisonneau** [comment]
🎁 5af705c should be allowing you to use the API @dmpvost :) you can use the latest release to leverage the feature, I have enabled it by default.

**Comment by dmpvost** [comment]
@mvisonneau

Thank!!! API is enable now! 👍 

But I'm getting an error with the API of docker,

I have take a simple example from https://github.com/benkeen/generatedata/tree/master/plugins/dataTypes/AutoIncrement
`{
    "numRows": 10,
    "rows": [
        {
            "type": "AutoIncrement",
            "title": "Simple increment",
            "settings": {
                "incrementStart": 1,
                "incrementValue": 1
            }
        },
        {
            "type": "AutoIncrement",
            "title": "Decrement with placeholder",
            "settings": {
                "incrementStart": 100,
                "incrementValue": -5,
                "incrementPlaceholder": "{$INCR}B"
            }
        }
    ],
    "export": {
        "type": "JSON",
        "settings": {
            "stripWhitespace": false,
            "dataStructureFormat": "complex"
        }
    }
}`


I have this answer

`{
    "error": "API_UNKNOWN_DATA_TYPE",
    "error_details": "invalid `type` attribute: `AutoIncrement`",
    "location": "index 0 of the `rows` array"
}`

Is it possible that the body is "cut" by NGINX, or not transmit?

I have try this code with generatedata (single project working with MAMP, running with php)
and it work

do you have any idea?

thank

**Comment by mvisonneau** [comment]
Not sure what your issue is related to, it works fine for me :

```json
# test.json
{
  "numRows": 10,
  "rows": [{
    "type": "AutoIncrement",
    "title": "Simple increment",
    "settings": {
      "incrementStart": 1,
      "incrementValue": 1
    }
  }, {
    "type": "AutoIncrement",
    "title": "Decrement with placeholder",
    "settings": {
      "incrementStart": 100,
      "incrementValue": -5,
      "incrementPlaceholder": "{$INCR}B"
    }
  }],
  "export": {
    "type": "JSON",
    "settings": {
      "stripWhitespace": false,
      "dataStructureFormat": "complex"
    }
  }
}
```

```json
~$ curl -s -d @test.json http://localhost:8000/api/v1/data | jq .
{
  "cols": [
    "Simple increment",
    "Decrement with placeholder"
  ],
  "data": [
    [
      1,
      "100B"
    ],
    [
      2,
      "95B"
    ],
    [
      3,
      "90B"
    ],
    [
      4,
      "85B"
    ],
    [
      5,
      "80B"
    ],
    [
      6,
      "75B"
    ],
    [
      7,
      "70B"
    ],
    [
      8,
      "65B"
    ],
    [
      9,
      "60B"
    ],
    [
      10,
      "55B"
    ]
  ]
}
```

**Comment by dmpvost** [comment]
I found the problem,

I have start docker-compose, and try directly to use the API, 
but we should init generate data with browser, and install all plugin, 
after that it work fine,
thank!
