### ISSUE TITLE
persisting config on docker reboot

### ISSUE THREAD

**Issue by Nonobis** [mvisonneau/docker-generatedata#6]
Hello,

Could you add persisting configuration on reboot ?
I am trying with a volume on "/opt/generatedata" but it's not working.

Thanks.

**Comment by mvisonneau** [comment]
👋 hey @Nonobis,

I am not sure to understand your request? Afaik, persistence configuration in containers can be achieved at runtime not build 🤔

**Comment by Nonobis** [comment]
sorry, problem solved :)
